### ISSUE TITLE
Unable to create Crisp client

### ISSUE THREAD

**Issue by eugene-kim** [crisp-im/node-crisp-api#49]
`new Crisp()` throw an error: results in `MODULE_NOT_FOUND` Error: 'Cannot find module './resources/BucketURL' 

Version `7.3.0`

```
{
    "stack": "Error: Cannot find module './resources/BucketURL'\nRequire stack:\n- /Users/eugenekim/Projects/crisp-writer/backend/.esbuild/.build/src/functions/pluginAction.js\n- /Users/eugenekim/Projects/crisp-writer/backend/node_modules/serverless-offline/src/lambda/handler-runner/in-process-runner/aws-lambda-ric/UserFunction.js\n    at ono3 (/Users/eugenekim/Projects/crisp-writer/backend/.esbuild/.build/src/functions/pluginAction.js:289:24)\n    at ono3 (/Users/eugenekim/Projects/crisp-writer/backend/.esbuild/.build/src/functions/pluginAction.js:339:25)\n    at handler (/Users/eugenekim/Projects/crisp-writer/backend/.esbuild/.build/src/functions/pluginAction.js:28371:43)\n    at InProcessRunner.run (file:///Users/eugenekim/Projects/crisp-writer/backend/node_modules/serverless-offline/src/lambda/handler-runner/in-process-runner/InProcessRunner.js:87:20)\n    at async MessagePort.<anonymous> (file:///Users/eugenekim/Projects/crisp-writer/backend/node_modules/serverless-offline/src/lambda/handler-runner/worker-thread-runner/workerThreadHelper.js:24:14)\n\nError: Cannot find module './resources/BucketURL'\nRequire stack:\n- /Users/eugenekim/Projects/crisp-writer/backend/.esbuild/.build/src/functions/pluginAction.js\n- /Users/eugenekim/Projects/crisp-writer/backend/node_modules/serverless-offline/src/lambda/handler-runner/in-process-runner/aws-lambda-ric/UserFunction.js\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:746:27)\n    at Module.require (internal/modules/cjs/loader.js:974:19)\n    at require (internal/modules/cjs/helpers.js:101:18)\n    at Crisp2._prepareResources (/Users/eugenekim/Projects/crisp-writer/backend/.esbuild/.build/src/functions/pluginAction.js:15335:37)\n    at Crisp2._prepareServices (/Users/eugenekim/Projects/crisp-writer/backend/.esbuild/.build/src/functions/pluginAction.js:15318:16)\n    at new Crisp2 (/Users/eugenekim/Projects/crisp-writer/backend/.esbuild/.build/src/functions/pluginAction.js:14965:12)\n    at handler (/Users/eugenekim/Projects/crisp-writer/backend/.esbuild/.build/src/functions/pluginAction.js:28341:25)\n    at InProcessRunner.run (file:///Users/eugenekim/Projects/crisp-writer/backend/node_modules/serverless-offline/src/lambda/handler-runner/in-process-runner/InProcessRunner.js:87:20)\n    at async MessagePort.<anonymous> (file:///Users/eugenekim/Projects/crisp-writer/backend/node_modules/serverless-offline/src/lambda/handler-runner/worker-thread-runner/workerThreadHelper.js:24:14)",
    "message": "Cannot find module './resources/BucketURL'\nRequire stack:\n- /Users/eugenekim/Projects/crisp-writer/backend/.esbuild/.build/src/functions/pluginAction.js\n- /Users/eugenekim/Projects/crisp-writer/backend/node_modules/serverless-offline/src/lambda/handler-runner/in-process-runner/aws-lambda-ric/UserFunction.js",
    "code": "MODULE_NOT_FOUND",
    "requireStack": [
        "/Users/eugenekim/Projects/crisp-writer/backend/.esbuild/.build/src/functions/pluginAction.js",
        "/Users/eugenekim/Projects/crisp-writer/backend/node_modules/serverless-offline/src/lambda/handler-runner/in-process-runner/aws-lambda-ric/UserFunction.js"
    ],
}
```

**Comment by eugene-kim** [comment]
Closing - this was related to `esbuild` and not the client. I had to declare the 'crisp-api' dependency as an external dependency

**Comment by baptistejamin** [comment]
Hi, our agents are offline at the moment. Please leave a message and we will get back to you as soon as possible.
